name: "Run ansible-lint with reviewdog"
description: "🐶 Run ansible-lint with reviewdog on pull requests to improve code review experience."
author: "takezyou"
inputs:
  github_token:
    description: "GITHUB_TOKEN"
    required: true
    default: ${{ github.token }}
  level:
    description: "Report level for reviewdog [info,warning,error]"
    default: "error"
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: "github-pr-check"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: "added"
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: "false"
  reviewdog_flags:
    description: "Additional reviewdog flags"
    default: ""
  workdir:
    description: "Working directory relative to the root directory."
    default: "."
  ansiblelint_version:
    description: "The ansible-lint version to use"
    default: "5.3.2"
  ansiblelint_flags:
    description: "Flags and args of ansible-lint command"
    default: ""

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      id: ansible-lint
      shell: bash
      env:
        # We may want to allow specifying reviewdog version as
        # action's input, but let's start with hard coded latest stable version for reviewdog
        REVIEWDOG_VERSION: v0.18.0
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_ANSIBLELINT_VERSION: ${{ inputs.ansiblelint_version }}
        INPUT_ANSIBLELINT_FLAGS: ${{ inputs.ansiblelint_flags }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.workdir }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}

branding:
  icon: "check-circle"
  color: "orange"
