name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.13"

      - name: ansible-lint github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          ansiblelint_flags: "testdata/test.yml"
