name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"

      - name: ansible-lint github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          ansiblelint_flags: "testdata/test.yml"
