name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"

      - name: ansible-lint github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          ansiblelint_flags: "testdata/test.yml"

      - name: ansible-lint github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          ansiblelint_flags: "testdata/test.yml"
